nguage: python
python:
        - "3.4"
        - "3.5"
install: 
        - "pip install -r requirements.txt --use-mirrors"
        - "pip install coverage"
        - "pip install coveralls"
script: 
        - "coverage run --source=aquaipy setup.py test"
after_success:
        coveralls            
