language: python
python:
  - 3.4
  - 3.5
  - 3.6
sudo: false
install:
  - travis_retry python setup.py develop
  - travis_retry pip install pytest-cov coverage coveralls
script:
  - coverage run --source=aquaipy setup.py test
after_success:
  coveralls
